export interface SeniorInterest {
  id: string;
  icon: string;
  labels: Record<string, string>;
  descriptions: Record<string, string>;
}

export const SENIOR_INTERESTS_LIST: SeniorInterest[] = [
  {
    id: "music",
    icon: "🎵",
    labels: {
      en: "Music & Songs",
      hi: "संगीत और गाने",
      as: "গান আৰু গীত",
      bn: "সঙ্গীত ও গান",
      gu: "સંગીત અને ગીતો",
      mr: "संगीत आणि गाणी",
      pa: "ਸੰਗੀਤ ਅਤੇ ਗੀਤ",
      or: "ସଙ୍ଗୀତ ଏବଂ ଗୀତ",
      ta: "இசை மற்றும் பாடல்கள்",
      te: "సంగీతం మరియు పాటలు",
      kn: "ಸಂಗೀತ ಮತ್ತು ಹಾಡುಗಳು",
      ml: "സംഗീതവും പാട്ടുകളും",
      ne: "संगीत र गीतहरू",
      brx: "मेन्थाइ आरो रोजाबनाय",
      kha: "Ki Jingrwai bad Sur",
      lus: "Hla leh Rimawi",
      mni: "ঈশৈ অমসুং সুর",
    },
    descriptions: {
      en: "Bhajans, classical melodies & evergreen favorites",
      hi: "भजन, शास्त्रीय धुनें और पुराने मधुर गीत",
      as: "ভজন, পুৰণি গীত আৰু লোকসংগীত",
      bn: "ভজন, পুরাতন গান ও শাস্ত্রীয় সুর",
      gu: "ભજન, જૂના ગીતો અને મધુર સંગીત",
      mr: "भजने, भावगीते आणि जुनी सदाबहार गाणी",
      pa: "ਭਜਨ, ਪੁਰਾਣੇ ਗੀਤ ਅਤੇ ਸ਼ਾਂਤ ਧੁਨਾਂ",
      or: "ଭଜନ, ପୁରୁଣା ଗୀତ ଏବଂ ଶାସ୍ତ୍ରୀୟ ଧୁନ୍",
      ta: "பக்திப் பாடல்கள் மற்றும் பழைய மெல்லிசைகள்",
      te: "భక్తి గీతాలు మరియు పాత మధుర గీతాలు",
      kn: "ಭಕ್ತಿಗೀತೆಗಳು ಮತ್ತು ಹಳೆಯ ಸುಮಧುರ ಹಾಡುಗಳು",
      ml: "ഭക്തിഗാനങ്ങളും പഴയ ലളിതഗാനങ്ങളും",
      ne: "भजन, शास्त्रीय धुन र पुराना मीठा गीतहरू",
      brx: "ईस्वरनि मेन्थाइ आरो गोजोन रोजाबनाय",
      kha: "Ki jingrwai niam bad ki sur ba sngewthiang",
      lus: "Pathian hla leh hla mawi tak takte",
      mni: "লৈশেম ঈশৈ অমসুং অরিবা সুরশিং",
    },
  },
  {
    id: "gardening",
    icon: "🌱",
    labels: {
      en: "Gardening & Nature",
      hi: "बागवानी और प्रकृति",
      as: "বাগিচা আৰু প্ৰকৃতি",
      bn: "বাগান ও প্রকৃতি",
      gu: "બાગકામ અને પ્રકૃતિ",
      mr: "बागकाम आणि निसर्ग",
      pa: "ਬਾਗਬਾਨੀ ਅਤੇ ਕੁਦਰਤ",
      or: "ବଗିଚା କାମ ଏବଂ ପ୍ରକୃତି",
      ta: "தோட்டக்கலை மற்றும் இயற்கை",
      te: "తోటపని మరియు ప్రకృతి",
      kn: "ತೋಟಗಾರಿಕೆ ಮತ್ತು ಪ್ರಕೃತಿ",
      ml: "തോട്ടപ്പണിയും പ്രകൃതിയും",
      ne: "बगैंचा र प्रकृति",
      brx: "बारि दानाय आरो मिथिंगा",
      kha: "Ka Kper bad ka Mariang",
      lus: "Huan siam leh Siamtu kut chhuak",
      mni: "লৈকোই অমসুং মহৌশাগী শক্তম",
    },
    descriptions: {
      en: "Plants, flowers, fresh morning breeze & greenery",
      hi: "पौधे, फूल, ताज़ी हवा और सुबह की हरियाली",
      as: "ফুল, গছ-গছনি আৰু সেউজ প্ৰকৃতিৰ পৰশ",
      bn: "গাছপালা, ফুল ও নির্মল সকালের বাতাস",
      gu: "છોડ, ફૂલો અને સવારની તાજી ખુશનુમા હવા",
      mr: "झाडे, फुले आणि सकाळची आल्हाददायक हवा",
      pa: "ਬੂਟੇ, ਫੁੱਲ ਅਤੇ ਸਵੇਰ ਦੀ ਤਾਜ਼ੀ ਹਵਾ",
      or: "ଗଛଲତା, ଫୁଲ ଏବଂ ସକାଳର ସତେଜ ପବନ",
      ta: "செடிகள், மலர்கள் மற்றும் காலை தென்றல்",
      te: "మొక్కలు, పూలు మరియు ఉదయపు స్వచ్ఛమైన గాలి",
      kn: "ಗಿಡಗಳು, ಹೂವುಗಳು ಮತ್ತು ಬೆಳಗಿನ ತಂಗಾಳಿ",
      ml: "ചെടികൾ, പൂക്കൾ, പുലർകാല തണുത്ത കാറ്റ്",
      ne: "बिरुवा, फूल र बिहानीको ताजा हावा",
      brx: "बिबार, बिफां आरो सिगांनि गोजां बार",
      kha: "Ki jingthung, syntiew bad ka lyer ba sngur",
      lus: "Pangpar leh thingphun enkawl nuam takte",
      mni: "লৈরাং, উপাল অমসুং অয়ুক্কী নুংশিৎ",
    },
  },
  {
    id: "stories",
    icon: "📖",
    labels: {
      en: "Stories & Reading",
      hi: "कहानियां और पढ़ना",
      as: "সাধু আৰু পাঠ",
      bn: "গল্প ও পাঠ",
      gu: "વાર્તાઓ અને વાંચન",
      mr: "गोष्टी आणि वाचन",
      pa: "ਕਹਾਣੀਆਂ ਅਤੇ ਪੜ੍ਹਨਾ",
      or: "ଗଳ୍ପ ଏବଂ ପଠନ",
      ta: "கதைகள் மற்றும் வாசிப்பு",
      te: "కథలు మరియు పఠనం",
      kn: "ಕಥೆಗಳು ಮತ್ತು ಓದುವಿಕೆ",
      ml: "കഥകളും വായനയും",
      ne: "कथा र पठन",
      brx: "सल' आरो फरायनाय",
      kha: "Ki Puriskam bad Pulekot",
      lus: "Thawnthu leh Lehkhabu chhiar",
      mni: "ৱারী অমসুং পাবা",
    },
    descriptions: {
      en: "Inspiring folktales, spiritual texts & memoirs",
      hi: "प्रेरक कहानियां, धार्मिक ग्रंथ और संस्मरण",
      as: "সাধুকথা, পুথি আৰু মন চুই যোৱা স্মৃতিচাৰণ",
      bn: "উপকথা, ধর্মীয় গ্রন্থ ও অনুপ্রেরণার গল্প",
      gu: "પ્રેરક વાર્તાઓ અને ધાર્મિક પુસ્તકોનું વાંચન",
      mr: "प्रेरणादायी कथा, संतसाहित्य आणि पुस्तके",
      pa: "ਪ੍ਰੇਰਣਾਦਾਇਕ ਕਹਾਣੀਆਂ ਅਤੇ ਧਾਰਮਿਕ ਸਾਹਿਤ",
      or: "ପ୍ରେରଣାଦାୟୀ ଗଳ୍ପ ଏବଂ ଆଧ୍ୟାତ୍ମିକ ପୁସ୍ତକ",
      ta: "ஊக்கமளிக்கும் கதைகள் மற்றும் ஆன்மீக நூல்கள்",
      te: "స్ఫూర్తిదాయక కథలు మరియు ఆధ్యాత్మిక గ్రంథాలు",
      kn: "ಸ್ಪೂರ್ತಿದಾಯಕ ಕಥೆಗಳು ಮತ್ತು ಧಾರ್મિક ಗ್ರಂಥಗಳು",
      ml: "പ്രചോദനാത്മക കഥകളും ആത്മീയ വായനയും",
      ne: "प्रेरक कथाहरू, धार्मिक पुस्तक र संस्मरण",
      brx: "सादिनि सल' आरो गोसोनि बाथ्रा",
      kha: "Ki puriskam hyndai bad ki kot kynja mynsiem",
      lus: "Thawnthu ngaihnawm leh rilru tihhlimna",
      mni: "ইথিল পীবা ৱারীশিং অমসুং লাইরিক",
    },
  },
  {
    id: "games",
    icon: "🧩",
    labels: {
      en: "Memory Games",
      hi: "स्मृति खेल",
      as: "স্মৃতি খেল",
      bn: "স্মৃতির খেলা",
      gu: "મગજની રમતો",
      mr: "स्मृती खेळ",
      pa: "ਦਿਮਾਗੀ ਖੇਡਾਂ",
      or: "ସ୍ମୃତି ଖେଳ",
      ta: "நினைவாற்றல் விளையாட்டுகள்",
      te: "జ్ఞాపకశక్తి ఆటలు",
      kn: "ನೆನಪಿನ ಆಟಗಳು",
      ml: "ഓർമ്മ ഗെയിമുകൾ",
      ne: "स्मृति खेलहरू",
      brx: "गोसोखांथि गेलेनाय",
      kha: "Ki Jingialehkai Kynmaw",
      lus: "Hriatna Infiamna",
      mni: "নিংশিং শান্নবা",
    },
    descriptions: {
      en: "Gentle puzzles, cards & calm brain exercises",
      hi: "आसान पहेलियां, पत्ते और दिमागी कसरत",
      as: "সহজ সাঁথৰ আৰু মন সতেজ ৰখা সহজ খেল",
      bn: "সহজ ধাঁধা ও মনকে সতেজ রাখার খেলা",
      gu: "સરળ કોયડા અને મગજની હળવી કસરત",
      mr: "सोपी कोडी आणि मन तल्लख ठेवणारे खेळ",
      pa: "ਸੌਖੀਆਂ ਬੁਝਾਰਤਾਂ ਅਤੇ ਦਿਮਾਗੀ ਅਭਿਆਸ",
      or: "ସହଜ ନଇଁବା ଏବଂ ମସ୍ତିଷ୍କ କସରତ ଖେଳ",
      ta: "எளிய விடுகதைகள் மற்றும் நினைவாற்றல் பயிற்சி",
      te: "సులభమైన పజిల్స్ మరియు మనస్సును చురుగ్గా ఉంచే ఆటలు",
      kn: "ಸರಳ ಒಗಟುಗಳು ಮತ್ತು ನೆನಪಿನ ವ್ಯಾಯಾಮಗಳು",
      ml: "ലളിതമായ പസിലുകളും ഓർമ്മ ശക്തിപ്പെടുത്തുന്ന കളികളും",
      ne: "सजिला पजल र मन शान्त पार्ने मानसिक अभ्यास",
      brx: "गोरलै गेलेनाय आरो गोसोनि गेवलांथि",
      kha: "Ki jingkyntip ba jem bad jingpynsngewbha ia ka bor pyrkhat",
      lus: "Rilru tiharh tura infiamna hahdam thlakte",
      mni: "লৈবাক অসিগী লাইবা পজলশিং অমসুং শান্নবা",
    },
  },
  {
    id: "yoga",
    icon: "🧘",
    labels: {
      en: "Yoga & Meditation",
      hi: "योग और ध्यान",
      as: "যোগ আৰু ধ্যান",
      bn: "যোগ ও ধ্যান",
      gu: "યોગ અને ધ્યાન",
      mr: "योग आणि ध्यान",
      pa: "ਯੋਗਾ ਅਤੇ ਧਿਆਨ",
      or: "ଯୋଗ ଏବଂ ଧ୍ୟାନ",
      ta: "யோகா மற்றும் தியானம்",
      te: "యోగా మరియు ధ్యానం",
      kn: "ಯೋಗ ಮತ್ತು ಧ್ಯಾನ",
      ml: "യോഗയും ധ്യാനവും",
      ne: "योग र ध्यान",
      brx: "य'गा आरो गोसो गोजোনनाय",
      kha: "Ka Yoga bad Jingpynleit Jingmut",
      lus: "Yoga leh Inngaihtuah hahdamna",
      mni: "যোগ অমসুং ধ্যান",
    },
    descriptions: {
      en: "Pranayama, calm breathing & peaceful relaxation",
      hi: "प्राणायाम, हल्का खिंचाव और मानसिक शांति",
      as: "প্ৰাণায়াম, সহজ যোগাসন আৰু শান্ত ধ্যান",
      bn: "প্রাণায়াম, হালকা আসন ও মানসিক প্রশান্তি",
      gu: "પ્રાણાયામ, હળવી કસરત અને શાંત મનનું ધ્યાન",
      mr: "प्राणायाम, हलके व्यायाम आणि मानसिक शांतता",
      pa: "ਪ੍ਰਾਣਾਯਾਮ, ਸ਼ਾਂਤ ਸਾਹ ਲੈਣਾ ਅਤੇ ਤਣਾਅ-ਮੁਕਤੀ",
      or: "ପ୍ରାଣାୟାମ, ସହଜ ଯୋଗାସନ ଏବଂ ମାନସିକ ଶାନ୍ତି",
      ta: "மூச்சுப் பயிற்சி மற்றும் அமைதியான தியானம்",
      te: "ప్రాణాయామం, సులభమైన ఆసనాలు మరియు ప్రశాంతత",
      kn: "ಪ್ರಾಣಾಯಾಮ ಮತ್ತು ಶಾಂತಿಯುತ ಧ್ಯಾನ",
      ml: "പ്രാണായാമവും മനസ്സിനെ ശാന്തമാക്കുന്ന ധ്യാനവും",
      ne: "प्राणायाम, हल्का व्यायाम र मानसिक शान्ति",
      brx: "हाबसिनाय बार आरो गोजोन मोननाय",
      kha: "Ka jingsumar mynsiem bad ka jingpyngngad jingmut",
      lus: "Thawk lak dan dik leh rilru thlamuanna",
      mni: "নুংশিৎ শেংহনবা অমসুং নুংঙাইবা ধ্যান",
    },
  },
  {
    id: "cooking",
    icon: "🍳",
    labels: {
      en: "Cooking & Recipes",
      hi: "खाना पकाना और व्यंजन",
      as: "ৰন্ধা-বঢ়া আৰু ব্যঞ্জন",
      bn: "রান্না ও রেসিপি",
      gu: "રસોઈ અને વાનગીઓ",
      mr: "स्वयंपाक आणि पाककृती",
      pa: "ਖਾਣਾ ਪਕਾਉਣਾ ਅਤੇ ਪਕਵਾਨ",
      or: "ରୋଷେଇ ଏବଂ ବ୍ୟଞ୍ଜନ",
      ta: "சமையல் மற்றும் சமையல் குறிப்புகள்",
      te: "వంటలు మరియు వంటకాలు",
      kn: "ಅಡುಗೆ ಮತ್ತು ಪಾಕವಿಧಾನಗಳು",
      ml: "പാചകവും രുചിക്കൂട്ടുകളും",
      ne: "खाना पकाउने र परिकार",
      brx: "संख्रुंनाय आरो जानाय-लोंनाय",
      kha: "Ka Shet ka Tiew",
      lus: "Chawhmeh siam leh Ei in",
      mni: "চাক-থোংবা অমসুং চান-থকনবা",
    },
    descriptions: {
      en: "Traditional tastes, healthy spices & kitchen stories",
      hi: "पारंपरिक स्वाद, पौष्टिक व्यंजन और रसोई की बातें",
      as: "ঘৰুৱা সোৱাদ, পৰম্পৰাগত খাদ্য আৰু ৰন্ধন প্ৰণালী",
      bn: "ঐতিহ্যবাহী স্বাদ, পুষ্টিকর খাবার ও রান্নার গল্প",
      gu: "પરંપરાગત સ્વાદિષ્ટ વાનગીઓ અને રસોઈની યાદો",
      mr: "पारंपरिक चव, पौष्टिक पदार्थ आणि घरगुती पाककृती",
      pa: "ਪਰੰਪਰਾਗਤ ਸਵਾਦ, ਸਿਹਤਮੰਦ ਖਾਣਾ ਅਤੇ ਮਨਪਸੰਦ ਪਕਵਾਨ",
      or: "ପାରମ୍ପରିକ ସ୍ୱାଦ, ସ୍ୱାସ୍ଥ୍ୟକର ଖାଦ୍ୟ ଏବଂ ରୋଷେଇ କଥା",
      ta: "பாரம்பரிய சுவைகள் மற்றும் ஆரோக்கியமான உணவுகள்",
      te: "సాంప్రదాయ వంటకాలు మరియు ఆరోగ్యకరమైన ఆహారాలు",
      kn: "ಸಾಂಪ್ರದಾಯಿಕ ಅಡುಗೆಗಳು ಮತ್ತು ಆರೋಗ್ಯಕರ ಆಹಾರ",
      ml: "പരമ്പരാഗത രുചികളും ആരോഗ്യകരമായ ഭക്ഷണരീതികളും",
      ne: "परम्परागत स्वाद, स्वास्थ्यकर परिकार र भान्साका कुरा",
      brx: "जोंनि ओनसोलनि संनाय-एवनाय",
      kha: "Ki jingbam tynrai bad ki rukom shet ba bang",
      lus: "Hmanlai chawhmeh tui takte leh a siam dan",
      mni: "লৈবাক অসিগী মহাও লৈবা চাক-ঈশৈ",
    },
  },
  {
    id: "culture",
    icon: "🛕",
    labels: {
      en: "Culture & Traditions",
      hi: "संस्कृति और परंपराएं",
      as: "সংস্কৃতি আৰু পৰম্পৰা",
      bn: "সংস্কৃতি ও ঐতিহ্য",
      gu: "સંસ્કૃતિ અને પરંપરા",
      mr: "संस्कृती आणि परंपरा",
      pa: "ਸੱਭਿਆਚਾਰ ਅਤੇ ਪਰੰਪਰਾਵਾਂ",
      or: "ସଂସ୍କୃତି ଏବଂ ପରମ୍ପରା",
      ta: "கலாச்சாரம் மற்றும் பாரம்பரியம்",
      te: "సంస్కృతి మరియు సంప్రదాయాలు",
      kn: "ಸಂಸ್ಕೃತಿ ಮತ್ತು ಸಂಪ್ರದಾಯಗಳು",
      ml: "സംസ്കാരവും പാരമ്പര്യവും",
      ne: "संस्कृति र परम्परा",
      brx: "जोंनि हारिमु आरो हुदा",
      kha: "Ka Kolshor bad Jingngeit Tynrai",
      lus: "Hnam zia rang leh Nunphung",
      mni: "নাৎ অমসুং চৎনবী",
    },
    descriptions: {
      en: "Festivals, holy shrines, sacred folklore & heritage",
      hi: "त्योहार, तीर्थ, उत्सव और गौरवशाली विरासत",
      as: "উৎসৱ, তিথি, মন্দিৰ আৰু আমাৰ অমূল্য ঐতিহ্য",
      bn: "উৎসব, তীর্থস্থান ও সমৃদ্ধ লোকসংস্কৃতি",
      gu: "તહેવારો, તીર્થધામો અને આપણો સાંસ્કૃતિક વારસો",
      mr: "सण-उत्सव, मंदिरे, तीर्थक्षेत्रे आणि समृद्ध वारसा",
      pa: "ਤਿਉਹਾਰ, ਇਤਿਹਾਸਕ ਅਸਥਾਨ ਅਤੇ ਅਮੀਰ ਵਿਰਸਾ",
      or: "ପର୍ବପର୍ବାଣି, ତୀର୍ଥସ୍ଥାନ ଏବଂ ସମୃଦ୍ଧ ଐତିହ୍ୟ",
      ta: "பண்டிகைகள், கோயில்கள் மற்றும் பாரம்பரிய பெருமைகள்",
      te: "పండుగలు, దేవాలయాలు మరియు పవిత్ర సంస్కృతి",
      kn: "ಹಬ್ಬಗಳು, ಪುಣ್ಯಕ್ಷೇತ್ರಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಪರಂಪರೆ",
      ml: "ഉത്സവങ്ങൾ, പുണ്യക്ഷേത്രങ്ങൾ, സമ്പന്നമായ പൈതൃകം",
      ne: "चाडपर्व, तीर्थस्थल र हाम्रो गौरवमय सम्पदा",
      brx: "बैसागु, फुजाहार आरो जोंनि दोहोरोम",
      kha: "Ki lehniam tynrai bad ki jaka mane ba kyntang",
      lus: "Kut leh hnam thawnthu ropui takte",
      mni: "কুহ্মৈ, লাইশঙ অমসুং পুরিবা নাৎ",
    },
  },
  {
    id: "family",
    icon: "👨‍👩‍👧",
    labels: {
      en: "Family & Memories",
      hi: "परिवार और यादें",
      as: "পৰিয়াল আৰু স্মৃতি",
      bn: "পরিবার ও স্মৃতি",
      gu: "કુટુંબ અને યાદો",
      mr: "कुटुंब आणि आठवणी",
      pa: "ਪਰਿਵਾਰ ਅਤੇ ਯਾਦਾਂ",
      or: "ପରିବାର ଏବଂ ସ୍ମୃତି",
      ta: "குடும்பம் மற்றும் நினைவுகள்",
      te: "కుటుంబం మరియు జ్ఞాపకాలు",
      kn: "ಕುಟುಂಬ ಮತ್ತು ನೆನಪುಗಳು",
      ml: "കുടുംബവും ഓർമ്മകളും",
      ne: "परिवार र सम्झनाहरू",
      brx: "नखर आरो गोसोखांथि",
      kha: "Ka Iing ka Sem bad Jingkynmaw",
      lus: "Chhungkua leh Hriatrengnate",
      mni: "ইমুং অমসুং নিংশিংবা",
    },
    descriptions: {
      en: "Children, grandchildren & golden family milestones",
      hi: "बच्चे, नाती-पोते और अनमोल पारिवारिक पल",
      as: "সন্তান, নাতি-নাতিনী আৰু পৰিয়ালৰ মৰমৰ ক্ষণ",
      bn: "সন্তান, নাতি-নাতনি ও পারিবারিক আনন্দঘন মুহূর্ত",
      gu: "સંતાનો, પૌત્રો અને વ્હાલા સ્વજનોની મીઠી ક્ષણો",
      mr: "मुले, नातवंडे आणि कुटुंबासोबत घालवलेले क्षण",
      pa: "ਬੱਚੇ, ਪੋਤੇ-ਪੋਤੀਆਂ ਅਤੇ ਪਰਿਵਾਰਕ ਯਾਦਾਂ",
      or: "ପିଲାମାନେ, ନାତିନାତୁଣୀ ଏବଂ ପାରିବାରିକ ମୁହୂର୍ତ୍ତ",
      ta: "பிள்ளைகள், பேரக்குழந்தைகள் மற்றும் குடும்ப தருணங்கள்",
      te: "పిల్లలు, మనవళ్లు మరియు కుటుంబ మధుర క్షణాలు",
      kn: "ಮಕ್ಕಳು, ಮೊಮ್ಮಕ್ಕಳು ಮತ್ತು ಕುಟುಂಬದ ಮಧುರ ನೆನಪುಗಳು",
      ml: "മക്കളും പേരക്കുട്ടികളും കുടുംബത്തോടൊപ്പമുള്ള നിമിഷങ്ങളും",
      ne: "छोराछोरी, नातिनातिना र परिवारका मीठा पलहरू",
      brx: "गथ'सा, आबौ-आबै आरो नखरनि मोजां मोननाय",
      kha: "Ki khun ki ksiew bad ki por ba kordor bad ka iing",
      lus: "Tu leh fate nena hun hman hlimawm takte",
      mni: "অঙাংশিং, শোইশবা অমসুং ইমুংগী নুংশিবা",
    },
  },
  {
    id: "movies",
    icon: "🎬",
    labels: {
      en: "Movies & Entertainment",
      hi: "सिनेमा और मनोरंजन",
      as: "চলচ্চিত্ৰ আৰু মনোৰঞ্জন",
      bn: "চলচ্চিত্র ও বিনোদন",
      gu: "સિનેમા અને મનોરંજન",
      mr: "चित्रपट आणि मनोरंजन",
      pa: "ਫ਼ਿਲਮਾਂ ਅਤੇ ਮਨੋਰੰਜਨ",
      or: "ଚଳଚ୍ଚିତ୍ର ଏବଂ ମନୋରଞ୍ଜନ",
      ta: "திரைப்படங்கள் மற்றும் பொழுதுபோக்கு",
      te: "సినిమాలు మరియు వినోదం",
      kn: "ಸಿನಿಮಾ ಮತ್ತು ಮನರಂಜನೆ",
      ml: "സിനിമയും വിനോദവും",
      ne: "चलचित्र र मनोरञ्जन",
      brx: "सावगारि आरो रंजानाय",
      kha: "Ki Phlim bad Jingpynbyrngia",
      lus: "Film leh Intihhlimna",
      mni: "মমো অমসুং নুংঙাইবা",
    },
    descriptions: {
      en: "Golden era cinema, comedy clips & classic stage plays",
      hi: "पुराना सुनहरा दौर, हास्य कार्यक्रम और नाटक",
      as: "সোণালী যুগৰ ছৱি, নাটক আৰু আনন্দদায়ক অনুষ্ঠান",
      bn: "সোনালী দিনের সিনেমা, হাস্যকৌতুক ও নাটক",
      gu: "સુવર્ણ કાળની યાદગાર ફિલ્મો, નાટક અને હાસ્ય",
      mr: "सुवर्णयुगातील चित्रपट, नाटके आणि जुने विनोद",
      pa: "ਪੁਰਾਣੀਆਂ ਕਲਾਸਿਕ ਫ਼ਿਲਮਾਂ ਅਤੇ ਹਾਸਰਸ ਪ੍ਰੋਗਰਾਮ",
      or: "ପୁରୁଣା ସୁବର୍ଣ୍ଣ ଯୁଗର ସିନେମା, ହାସ୍ୟ ଏବଂ ନାଟକ",
      ta: "பழைய கிளாசிக் படங்கள், நகைச்சுவை மற்றும் நாடகங்கள்",
      te: "స్వర్ణయుగ సినిమాలు, హాస్య సన్నివేశాలు మరియు నాటకాలు",
      kn: "ಹಳೆಯ ಸುವರ್ಣ ಯುಗದ ಚಲನಚಿತ್ರಗಳು ಮತ್ತು ಹಾಸ್ಯ ನಾಟಕಗಳು",
      ml: "പഴയ സുവർണ്ണകാല സിനിമകളും തമാശ പരിപാടികളും",
      ne: "सुनौलो युगका चलचित्र, हास्य र नाटकहरू",
      brx: "गोदोनि सावगारि आरो मिनिनाय हाबाफारि",
      kha: "Ki phlim hyndai bad ki drama ba pynbyrngia",
      lus: "Hmanlai film ngaihnawm leh intihhlimna",
      mni: "অরিবা গোল্ডেন ইরা সিনেমা অমসুং নোমহনবা",
    },
  },
  {
    id: "news",
    icon: "📰",
    labels: {
      en: "News & Current Affairs",
      hi: "समाचार और देश-दुनिया",
      as: "বাতৰি আৰু চলিত বিষয়",
      bn: "খবর ও সমসাময়িক",
      gu: "સમાચાર અને વર્તમાન",
      mr: "बातम्या आणि चालू घडामोडी",
      pa: "ਖ਼ਬਰਾਂ ਅਤੇ ਸਮਕਾਲੀ ਮਾਮਲੇ",
      or: "ଖବର ଏବଂ ଚଳିତ ଘଟଣାବଳୀ",
      ta: "செய்திகள் மற்றும் நடப்பு நிகழ்வுகள்",
      te: "వార్తలు మరియు వర్తమాన వ్యవహారాలు",
      kn: "ಸುದ್ದಿ ಮತ್ತು ಪ್ರಚಲಿತ ವಿದ್ಯಮಾನಗಳು",
      ml: "വാർത്തകളും സമകാലിക സംഭവങ്ങളും",
      ne: "समाचार र समसामयिक",
      brx: "राधাব आरो हादोरनि बाथ्रा",
      kha: "Ki Khubor bad ki Jingjia Mynta",
      lus: "Chanchinthar leh Thil thleng tharte",
      mni: "পাউ অমসুং লৈবাক্কী শক্তম",
    },
    descriptions: {
      en: "Morning headlines, regional bulletins & weather updates",
      hi: "रोज़ की ताज़ा ख़बरें, प्रांतीय समाचार और मौसम",
      as: "দৈনন্দিন বাতৰি, ৰাজ্যিক খবৰ আৰু বতৰৰ বতৰা",
      bn: "প্রতিদিনের তাজা খবর, স্থানীয় সংবাদ ও আবহাওয়া",
      gu: "રોજબરોજના મુખ્ય સમાચારો અને હવામાનની માહિતી",
      mr: "रोजच्या महत्त्वाच्या बातम्या आणि हवामान अंदाज",
      pa: "ਸਵੇਰ ਦੀਆਂ ਮੁੱਖ ਖ਼ਬਰਾਂ ਅਤੇ ਮੌਸਮ ਦਾ ਹਾਲ",
      or: "ଦୈନନ୍ଦିନ ମୁଖ୍ୟ ଖବର, ଆଞ୍ଚଳିକ ସୂଚନା ଏବଂ ପାଣିପାଗ",
      ta: "தினசரி முக்கிய செய்திகள் மற்றும் வானிலை நிலவரம்",
      te: "రోజువారీ ముఖ్యాంశాలు మరియు వాతావరణ సమాచారం",
      kn: "ದೈನಂದಿನ ಮುಖ್ಯಾಂಶಗಳು ಮತ್ತು ಹವಾಮಾನ ಮಾಹಿತಿ",
      ml: "ദൈനംദിന വാർത്തകളും പ്രാദേശിക വിവരങ്ങളും",
      ne: "दैनिक मुख्य समाचार, क्षेत्रीय खबर र मौसम",
      brx: "फुंनि रादाब आरो बारहावा खौरां",
      kha: "Ki khubor man ka sngi bad jingjia ha shnong ha thaw",
      lus: "Tualchhung chanchinthar leh khawchin duangte",
      mni: "অয়ুক্কী পাউ অমসুং নুংশিৎ-ঈশিংগী ফীভম",
    },
  },
  {
    id: "walking",
    icon: "🚶",
    labels: {
      en: "Walking & Daily Activities",
      hi: "टहलना और दिनचर्या",
      as: "খোজ কঢ়া আৰু দৈনন্দিন কাম",
      bn: "হাঁটা ও দৈনন্দিন কাজ",
      gu: "ચાલવું અને દિનચર્યા",
      mr: "चालणे आणि दैनंदिन कामे",
      pa: "ਸੈਰ ਅਤੇ ਰੋਜ਼ਾਨਾ ਗਤੀਵਿਧੀਆਂ",
      or: "ଚାଲିବା ଏବଂ ଦୈନନ୍ଦିନ କାର୍ଯ୍ୟ",
      ta: "நடைப்பயிற்சி மற்றும் அன்றாட செயல்பாடுகள்",
      te: "నడక మరియు రోజువారీ కార్యకలాపాలు",
      kn: "ನಡಿಗೆ ಮತ್ತು ದಿನಚರಿ",
      ml: "നടത്തവും ദൈനംദിന കാര്യങ്ങളും",
      ne: "हिँड्ने र दैनिक क्रियाकलाप",
      brx: "थाबायनाय आरो सानফ্রোमबोनि हाबा",
      kha: "Ka leit Shangkai bad Kam man ka sngi",
      lus: "Vakchhuah leh Nitin chetzia",
      mni: "খোঙনা চৎপা অমসুং নোংমগী থবক",
    },
    descriptions: {
      en: "Gentle morning strolls, fresh air & staying active",
      hi: "सुबह की ताज़ी सैर, हल्का व्यायाम और सक्रिय जीवन",
      as: "পুৱাৰ খোজ কঢ়া, পাতল সঞ্চালন আৰু সক্ৰিয় জীৱন",
      bn: "সকালের নিয়মিত পায়চারি, হালকা ব্যায়াম ও সতেজ মন",
      gu: "સવારની તાજગીભરી સહેલ અને શરીરને સક્રિય રાખવું",
      mr: "सकाळचे फिरणे, हलका व्यायाम आणि निरोगी सवयी",
      pa: "ਸਵੇਰ ਦੀ ਸੈਰ ਅਤੇ ਸਰੀਰ ਨੂੰ ਚੁਸਤ ਰੱਖਣਾ",
      or: "ସକାଳେ ଚାଲିବା, ହାଲୁକା ବ୍ୟାୟାମ ଏବଂ ସକ୍ରିୟ ଜୀବନ",
      ta: "காலை நடைப்பயிற்சி மற்றும் சுறுசுறுப்பான வாழ்க்கை",
      te: "ఉదయపు నడక, తేలికపాటి వ్యాయామం మరియు ఉత్తేజం",
      kn: "ಬೆಳಗಿನ ನಡಿಗೆ ಮತ್ತು ಚಟುವಟಿಕೆಯಿಂದ ಇರುವುದು",
      ml: "പ്രഭാത നടത്തവും ഊർജ്ജസ്വലമായ ജീവിതരീതിയും",
      ne: "बिहानीको घुमघाम र सक्रिय जीवनशैली",
      brx: "फुंनि थाबायनाय आरो सानफ्रोमनि गोहो",
      kha: "Ka jingiaidkai ha ka lyer ba sngur ban koit ban khiah",
      lus: "Tukthuan ei hmaa lenharh leh chetzial nuam takte",
      mni: "অয়ুক্কী খোঙচৎ অমসুং হকচাং হকচাংবা থবক",
    },
  },
  {
    id: "shopping",
    icon: "🛍️",
    labels: {
      en: "Shopping & Market",
      hi: "खरीदारी और बाज़ार",
      as: "বজাৰ আৰু কেনাকাটা",
      bn: "কেনাকাটা ও বাজার",
      gu: "ખરીદી અને બજાર",
      mr: "खरेदी आणि बाजार",
      pa: "ਖਰੀਦਦਾਰੀ ਅਤੇ ਬਾਜ਼ਾਰ",
      or: "କିଣାକିଣି ଏବଂ ବଜାର",
      ta: "ஷாப்பிங் மற்றும் சந்தை",
      te: "షాపింగ్ మరియు మార్కెట్",
      kn: "ಖರೀದಿ ಮತ್ತು ಮಾರುಕಟ್ಟೆ",
      ml: "ഷോപ്പിംഗും വിപണിയും",
      ne: "किनमेल र बजार",
      brx: "हाथाइ थांनाय आरो बेसाद बायनाय",
      kha: "Ka Leit Iew Leit Hat",
      lus: "Bazar leh Thil lei",
      mni: "কৈথেল চৎপা অমসুং পোৎ লৈবা",
    },
    descriptions: {
      en: "Local bazaar visits, seasonal fruits & household goods",
      hi: "स्थानीय बाज़ार, फल-सब्ज़ी और ज़रूरत का सामान",
      as: "ঘৰৰ ওচৰৰ বজাৰ, সতেজ ফল-মূল আৰু ক্ৰয়-বিক্ৰয়",
      bn: "কাছের বাজার, তাজা ফলমূল ও নিত্যপ্রয়োজনীয় জিনিস",
      gu: "સ્થાનિક બજારની મુલાકાત, તાજા ફળો અને જીવનજરૂરી ચીજો",
      mr: "स्थानिक बाजार, भाजीपाला आणि आवश्यक वस्तूंची खरेदी",
      pa: "ਸਥਾਨਕ ਬਾਜ਼ਾਰ ਜਾਣਾ, ਤਾਜ਼ੇ ਫਲ ਅਤੇ ਜ਼ਰੂਰੀ ਚੀਜ਼ਾਂ",
      or: "ସ୍ଥାନୀୟ ବଜାର, ତାଜା ଫଳ ଏବଂ ଘରୋଇ ଜିନିଷପତ୍ର",
      ta: "உள்ளூர் சந்தை, புதிய பழங்கள் மற்றும் வீட்டுப் பொருட்கள்",
      te: "స్థానిక మార్కెట్, తాజా పండ్లు మరియు నిత్యావసరాలు",
      kn: "ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ, ತಾಜಾ ಹಣ್ಣುಗಳು ಮತ್ತು ದಿನಸಿ ಸಾಮಗ್ರಿಗಳು",
      ml: "നാട്ടുചന്തകൾ, പുതിയ പഴങ്ങൾ, ആവശ്യസാധനങ്ങൾ",
      ne: "स्थानीय बजार, ताजा फलफूल र घरायसी सामान",
      brx: "गामिनि हाथाइ आरो गोथां फिथाइ-सामथाइ",
      kha: "Ka leit iew ban thied jhur bad ki mar iing",
      lus: "Bazar-a thil tharlam lei leh tlawhkual vel",
      mni: "কৈথেলগী উইরোই-চীঙ্গোই অমসুং পোৎলমশিং",
    },
  },
];

export interface SeniorInterestTexts {
  title: string;
  subtitle: string;
  continueBtn: string;
  backBtn: string;
  selectAlert: string;
  selectedCount: string;
  stepIndicator: string;
}

export const SENIOR_INTERESTS_PAGE_TEXTS: Record<string, SeniorInterestTexts> = {
  en: {
    title: "What are you interested in?",
    subtitle: "Choose your preferences so Memory Bond can tailor your experience to you.",
    continueBtn: "Continue",
    backBtn: "Back",
    selectAlert: "Please select at least 1 interest to continue.",
    selectedCount: "selected",
    stepIndicator: "Step 2 of 3",
  },
  hi: {
    title: "आपको किस चीज़ में रुचि है?",
    subtitle: "आप अपनी पसंद चुनें, ताकि Memory Bond आपके अनुभव को आपके अनुसार बेहतर बना सके।",
    continueBtn: "आगे बढ़ें",
    backBtn: "पीछे जाएं",
    selectAlert: "कृपया आगे बढ़ने के लिए कम से कम 1 रुचि चुनें।",
    selectedCount: "चुनी गई",
    stepIndicator: "चरण 2 / 3",
  },
  as: {
    title: "আপোনাৰ কি বিষয়ত ৰুচি আছে?",
    subtitle: "আপোনাৰ পছন্দ বাছনি কৰক, যাতে Memory Bond য়ে আপোনাৰ অভিজ্ঞতা আপোনাৰ বাবে অধিক সুন্দৰ কৰি তুলিব পাৰে।",
    continueBtn: "আগলৈ যাওক",
    backBtn: "পিছলৈ",
    selectAlert: "অনুগ্ৰহ কৰি আগবাঢ়িবলৈ কমেও ১ টা বিষয় বাছনি কৰক।",
    selectedCount: "বাছনি কৰা হৈছে",
    stepIndicator: "পদক্ষেপ ২ / ৩",
  },
  bn: {
    title: "আপনার কোন বিষয়ে আগ্রহ আছে?",
    subtitle: "আপনার পছন্দ নির্বাচন করুন, যাতে Memory Bond আপনার অভিজ্ঞতা আপনার মতো করে আরও সুন্দর করতে পারে।",
    continueBtn: "এগিয়ে চলুন",
    backBtn: "পেছনে",
    selectAlert: "এগিয়ে যেতে দয়া করে অন্তত ১টি পছন্দ নির্বাচন করুন।",
    selectedCount: "নির্বাচিত",
    stepIndicator: "ধাপ ২ / ৩",
  },
  gu: {
    title: "તમને કઈ બાબતમાં રસ છે?",
    subtitle: "તમારી પસંદગી પસંદ કરો, જેથી Memory Bond તમારા અનુભવને તમારા અનુસાર વધુ સારો બનાવી શકે.",
    continueBtn: "આગળ વધો",
    backBtn: "પાછળ",
    selectAlert: "કૃપા કરીને આગળ વધવા માટે ઓછામાં ઓછી 1 પસંદગી કરો.",
    selectedCount: "પસંદ કરેલ",
    stepIndicator: "પગલું ૨ / ૩",
  },
  mr: {
    title: "तुम्हाला कोणत्या गोष्टीत आवड आहे?",
    subtitle: "तुमची आवड निवडा, जेणेकरून Memory Bond तुमचा अनुभव आणखी चांगला करू शकेल.",
    continueBtn: "पुढे जा",
    backBtn: "मागे",
    selectAlert: "कृपया पुढे जाण्यासाठी किमान 1 आवड निवडा.",
    selectedCount: "निवडलेले",
    stepIndicator: "टप्पा २ / ३",
  },
  pa: {
    title: "ਤੁਹਾਨੂੰ ਕਿਸ ਚੀਜ਼ ਵਿੱਚ ਰੁਚੀ ਹੈ?",
    subtitle: "ਆਪਣੀ ਪਸੰਦ ਚੁਣੋ, ਤਾਂ ਜੋ Memory Bond ਤੁਹਾਡੇ ਤਜ਼ਰਬੇ ਨੂੰ ਤੁਹਾਡੇ ਅਨੁਸਾਰ ਬਿਹਤਰ ਬਣਾ ਸਕੇ।",
    continueBtn: "ਅੱਗੇ ਵਧੋ",
    backBtn: "ਪਿੱਛੇ",
    selectAlert: "ਕਿਰਪਾ ਕਰਕੇ ਅੱਗੇ ਵਧਣ ਲਈ ਘੱਟੋ-ਘੱਟ 1 ਪਸੰਦ ਚੁਣੋ।",
    selectedCount: "ਚੁਣਿਆ ਗਿਆ",
    stepIndicator: "ਪੜਾਅ 2 / 3",
  },
  or: {
    title: "ଆପଣଙ୍କର କେଉଁଥିରେ ରୁଚି ଅଛି?",
    subtitle: "ଆପଣଙ୍କର ପସନ୍ଦ ବାଛନ୍ତୁ, ଯାହାଦ୍ୱାରା Memory Bond ଆପଣଙ୍କ ଅନୁଭବକୁ ଅଧିକ ଉତ୍ତମ କରିପାରିବ।",
    continueBtn: "ଆଗକୁ ବଢ଼ନ୍ତୁ",
    backBtn: "ପଛକୁ",
    selectAlert: "ଆଗକୁ ବଢ଼ିବା ପାଇଁ ଦୟାକରି ଅତି କମରେ ୧ଟି ପସନ୍ଦ ବାଛନ୍ତୁ।",
    selectedCount: "ଚୟନ ହୋଇଛି",
    stepIndicator: "ପାଦ ୨ / ୩",
  },
  ta: {
    title: "உங்களுக்கு எதில் ஆர்வம் உள்ளது?",
    subtitle: "உங்கள் விருப்பங்களைத் தேர்வுசெய்யுங்கள், அதனால் Memory Bond உங்கள் அனுபவத்தை மேம்படுத்தும்.",
    continueBtn: "தொடரவும்",
    backBtn: "பின்செல்",
    selectAlert: "தொடர குறைந்தது 1 ஆர்வத்தைத் தேர்ந்தெடுக்கவும்.",
    selectedCount: "தேர்ந்தெடுக்கப்பட்டது",
    stepIndicator: "படி 2 / 3",
  },
  te: {
    title: "మీకు దేనిపై ఆసక్తి ఉంది?",
    subtitle: "మీ ప్రాధాన్యతలను ఎంచుకోండి, తద్వారా Memory Bond మీ అనుభవాన్ని మెరుగుపరుస్తుంది.",
    continueBtn: "కొనసాగించండి",
    backBtn: "వెనుకకు",
    selectAlert: "కొనసాగడానికి దయచేసి కనీసం 1 ఆసక్తిని ఎంచుకోండి.",
    selectedCount: "ఎంచుకోబడింది",
    stepIndicator: "దశ 2 / 3",
  },
  kn: {
    title: "ನಿಮಗೆ ಯಾವುದರಲ್ಲಿ ಆಸಕ್ತಿಯಿದೆ?",
    subtitle: "ನಿಮ್ಮ ಆಯ್ಕೆಗಳನ್ನು ಆರಿಸಿ, ಇದರಿಂದ Memory Bond ನಿಮ್ಮ ಅನುಭವವನ್ನು ಉತ್ತಮಗೊಳಿಸುತ್ತದೆ.",
    continueBtn: "ಮುಂದುವರಿಯಿರಿ",
    backBtn: "ಹಿಂದೆ",
    selectAlert: "ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ಕನಿಷ್ಠ 1 ಆಸಕ್ತಿಯನ್ನು ಆರಿಸಿ.",
    selectedCount: "ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ",
    stepIndicator: "ಹಂತ ೨ / ೩",
  },
  ml: {
    title: "നിങ്ങൾക്ക് എന്തിലാണ് താൽപ്പര്യം?",
    subtitle: "നിങ്ങളുടെ താൽപ്പര്യങ്ങൾ തിരഞ്ഞെടുക്കുക, അതുവഴി Memory Bond നിങ്ങളുടെ അനുഭവം മെച്ചപ്പെടുത്തും.",
    continueBtn: "തുടരുക",
    backBtn: "പിന്നിലേക്ക്",
    selectAlert: "തുടരുന്നതിന് ദയവായി കുറഞ്ഞത് 1 താൽപ്പര്യമെങ്കിലും തിരഞ്ഞെടുക്കുക.",
    selectedCount: "തിരഞ്ഞെടുത്തു",
    stepIndicator: "ഘട്ടം 2 / 3",
  },
  ne: {
    title: "तपाईंलाई के कुरामा रुचि छ?",
    subtitle: "आफ्नो रुचि छान्नुहोस्, ताकि Memory Bond ले तपाईंको अनुभव अझ राम्रो बनाउन सकोस्।",
    continueBtn: "अगाडि बढ्नुहोस्",
    backBtn: "पछाडि",
    selectAlert: "कृपया अगाडि बढ्न कम्तीमा १ रुचि छान्नुहोस्।",
    selectedCount: "छानियो",
    stepIndicator: "चरण २ / ३",
  },
  brx: {
    title: "नोंथांहा मा जिउनाव गोसो दं?",
    subtitle: "नोंथांनि मोजां मोननायखौ सायख' जाहाथे Memory Bond नोंथांनि थाखाय साबसिन जानो हागोन।",
    continueBtn: "सिगां थां",
    backBtn: "उनाव",
    selectAlert: "सिगां थांनो थाखाय अननानै खमैबो मोनसे मोजां मोननाय सायख'。",
    selectedCount: "सायख'नाय जाबाय",
    stepIndicator: "खोन्दो २ / ३",
  },
  kha: {
    title: "Kae kiei kiba phi sngewtynnat?",
    subtitle: "Jied ia ki jingieit jong phi khnang ba ka Memory Bond kan pynbha ia ka jingshem jong phi.",
    continueBtn: "Iaid sha khmat",
    backBtn: "Dien",
    selectAlert: "Sngewbha jied tang 1 tylli ruh ka jingieit ban iaid shakhmat.",
    selectedCount: "la jied",
    stepIndicator: "Jingjam 2 na 3",
  },
  lus: {
    title: "Eng thil nge i ngainat zawng?",
    subtitle: "I ngainat zawng thlang rawh, tichuan Memory Bond hian a tih nuam zual ang che.",
    continueBtn: "Kal zel rawh",
    backBtn: "Kir leh",
    selectAlert: "Kal zel turin ngainat zawng 1 tal thlang rawh le.",
    selectedCount: "thlan tawh",
    stepIndicator: "Kalhmang 2 na 3",
  },
  mni: {
    title: "নহাক্না করিদা অপাম্বা লৈবগে?",
    subtitle: "নহাক্কী পাম্বা খনবিয়ু, মসিনা Memory Bond না নহাক্কী পুন্সি মহাওবু হেন্না ফগৎহনগনি।",
    continueBtn: "মাংলোইদা চৎলু",
    backBtn: "হঞ্জিল্লু",
    selectAlert: "মাংলোইদা চৎনবা য়ামদ্রবদা অপাম্বা ১ খনবিয়ু।",
    selectedCount: "খনখ্রবা",
    stepIndicator: "তাঙ্কক ২ / ৩",
  },
};

export function getSeniorInterestsTexts(lang: string, parentFallback?: string): SeniorInterestTexts {
  if (SENIOR_INTERESTS_PAGE_TEXTS[lang]) return SENIOR_INTERESTS_PAGE_TEXTS[lang];
  if (parentFallback && SENIOR_INTERESTS_PAGE_TEXTS[parentFallback]) {
    return SENIOR_INTERESTS_PAGE_TEXTS[parentFallback];
  }
  return SENIOR_INTERESTS_PAGE_TEXTS["en"];
}

export function getLocalizedInterest(
  interest: SeniorInterest,
  lang: string,
  parentFallback?: string
): { label: string; desc: string } {
  const label =
    interest.labels[lang] ||
    (parentFallback && interest.labels[parentFallback]) ||
    interest.labels["en"] ||
    interest.id;
  const desc =
    interest.descriptions[lang] ||
    (parentFallback && interest.descriptions[parentFallback]) ||
    interest.descriptions["en"] ||
    "";
  return { label, desc };
}
