/**
 * NER Smart Logistics Demo Dataset
 * High-fidelity, geographically accurate sample data covering the 8 North Eastern States:
 * Assam, Meghalaya, Arunachal Pradesh, Manipur, Nagaland, Mizoram, Tripura, and Sikkim.
 *
 * CRITICAL COMPLIANCE:
 * All records are visibly flagged with `is_demo: true` and `source: "Demo / Simulated Data"`.
 * Never presented as live telematics unless an actual external API is connected.
 */

import type {
  RoadStatus,
  BridgeStatus,
  DisruptionRisk,
  RouteSuggestion,
  TravelDelayRecord,
  VehicleTrackingRecord,
  EssentialShipmentRecord,
  BlockedRoadAlert,
  FieldIncidentReport,
  DistrictConnectivityRecord,
  LogisticsBottleneck,
  EmergencyRoute,
  WeatherDataRecord,
  TransportDataSource,
} from "@/types/nerLogistics";

const NOW = new Date().toISOString();
const TEN_MINS_AGO = new Date(Date.now() - 10 * 60 * 1000).toISOString();
const THIRTY_MINS_AGO = new Date(Date.now() - 30 * 60 * 1000).toISOString();
const TWO_HOURS_AGO = new Date(Date.now() - 120 * 60 * 1000).toISOString();

// ---------------------------------------------------------------------------
// 1. ROADS STATUS
// ---------------------------------------------------------------------------
export const DEMO_ROADS: RoadStatus[] = [
  {
    id: "road-1",
    route_name: "NH-27 East-West Corridor (Lumding - Haflong - Silchar)",
    highway_number: "NH-27",
    location: "Jatinga Valley km 142",
    district: "Dima Hasao",
    state: "Assam",
    status: "BLOCKED",
    status_label: "Currently blocked",
    incident_information: "Massive mudslide triggered by overnight cloudburst. Clearing machinery deployed.",
    affected_stretch_km: 8.5,
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (NHAI NER Division Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "road-2",
    route_name: "NH-6 Guwahati - Shillong - Jowai - Silchar",
    highway_number: "NH-6",
    location: "Sonapur Tunnel bypass",
    district: "East Jaintia Hills",
    state: "Meghalaya",
    status: "PARTIAL",
    status_label: "Limited accessibility",
    incident_information: "Single lane vehicular traffic due to rockfall debris clearance. Heavy trucks regulated.",
    affected_stretch_km: 3.2,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Dataset (Meghalaya PWD Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "road-3",
    route_name: "NH-27 Guwahati Bypass (Khanapara - Jalukbari)",
    highway_number: "NH-27",
    location: "Boragaon Flyover",
    district: "Kamrup Metropolitan",
    state: "Assam",
    status: "OPEN",
    status_label: "Accessible",
    incident_information: "Normal all-weather traffic flow. Surface dry and clear.",
    affected_stretch_km: 0,
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (Assam State Transport Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "road-4",
    route_name: "Bhalukpong - Bomdila - Tawang Highway",
    highway_number: "NH-13 / Trans-Arunachal",
    location: "Sela Pass High Elevation Section",
    district: "West Kameng",
    state: "Arunachal Pradesh",
    status: "PARTIAL",
    status_label: "Limited accessibility",
    incident_information: "Dense morning fog and light scree slide near Sela Tunnel portal. 4WD recommended.",
    affected_stretch_km: 12.0,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Dataset (BRO Project Vartak Simulation)",
    is_demo: true,
    verification_status: "COMMUNITY_REPORTED",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "road-5",
    route_name: "NH-2 Kohima - Imphal Highway",
    highway_number: "NH-2",
    location: "Mao Gate Border Section",
    district: "Senapati",
    state: "Manipur",
    status: "OPEN",
    status_label: "Accessible",
    incident_information: "Convoy escort active for essential goods carriers. Road surface operational.",
    affected_stretch_km: 0,
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (Manipur Transport Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "road-6",
    route_name: "NH-10 Sevoke - Teesta - Gangtok",
    highway_number: "NH-10",
    location: "29th Mile Teesta River Stretch",
    district: "East Sikkim / Kalimpong border",
    state: "Sikkim",
    status: "BLOCKED",
    status_label: "Currently blocked",
    incident_information: "Teesta river water level rise caused embankment scour. Diverted via Mungpoo.",
    affected_stretch_km: 5.0,
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (Sikkim SDRF Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "road-7",
    route_name: "NH-306 Silchar - Vairengte - Aizawl",
    highway_number: "NH-306",
    location: "Kolosib Hill Ghat Section",
    district: "Kolasib",
    state: "Mizoram",
    status: "OPEN",
    status_label: "Accessible",
    incident_information: "Clear conditions. Essential petroleum tankers moving routinely.",
    affected_stretch_km: 0,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Dataset (Mizoram PWD Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "road-8",
    route_name: "NH-8 Agartala - Udaipur - Sabroom",
    highway_number: "NH-8",
    location: "Bishalgarh corridor",
    district: "Sepahijala",
    state: "Tripura",
    status: "OPEN",
    status_label: "Accessible",
    incident_information: "Paved 4-lane section completely operational.",
    affected_stretch_km: 0,
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (Tripura Transport Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 2. BRIDGES STATUS
// ---------------------------------------------------------------------------
export const DEMO_BRIDGES: BridgeStatus[] = [
  {
    id: "bridge-1",
    bridge_name: "Saraighat Old & New Bridges",
    river: "Brahmaputra River",
    route_name: "NH-27 Guwahati North-South Link",
    district: "Kamrup Metropolitan",
    state: "Assam",
    status: "OPEN",
    status_label: "Accessible",
    weight_restriction_tonnes: 45,
    incident_information: "Structural sensors reporting normal load deflection. Both spans open.",
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (N.F. Railway & NHAI Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "bridge-2",
    bridge_name: "Bogibeel Rail-cum-Road Bridge",
    river: "Brahmaputra River",
    route_name: "Dibrugarh - Dhemaji Link",
    district: "Dibrugarh",
    state: "Assam",
    status: "OPEN",
    status_label: "Accessible",
    weight_restriction_tonnes: 50,
    incident_information: "Upper deck road open for all essential transport and passenger vehicles.",
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Dataset (State PWD Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "bridge-3",
    bridge_name: "Doyang Bailey Bridge",
    river: "Doyang River",
    route_name: "Wokha - Mokokchung Road",
    district: "Wokha",
    state: "Nagaland",
    status: "PARTIAL",
    status_label: "Limited accessibility",
    weight_restriction_tonnes: 12,
    incident_information: "Single vehicle passage only. Heavy 16-wheeler cargo restricted.",
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Dataset (Nagaland Works Dept Simulation)",
    is_demo: true,
    verification_status: "COMMUNITY_REPORTED",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "bridge-4",
    bridge_name: "Bhalukpong Subansiri Tributary Bridge",
    river: "Kameng River",
    route_name: "NH-13 Gateway",
    district: "West Kameng",
    state: "Arunachal Pradesh",
    status: "BLOCKED",
    status_label: "Currently blocked",
    weight_restriction_tonnes: 0,
    incident_information: "Emergency abutment repair underway following boulder impact. Light vehicles diverted to military pontoon bridge.",
    last_updated: TEN_MINS_AGO,
    source: "Demo Dataset (BRO Project Simulation)",
    is_demo: true,
    verification_status: "OFFICIAL_VERIFIED",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 3. DISRUPTION RISK PREDICTIONS
// ---------------------------------------------------------------------------
export const DEMO_DISRUPTION_RISKS: DisruptionRisk[] = [
  {
    id: "risk-1",
    location: "Haflong - Harangajao Hill Gradient",
    district: "Dima Hasao",
    state: "Assam",
    risk_type: "landslide",
    risk_level: "CRITICAL",
    expected_time_window: "Next 6 to 18 hours",
    confidence_percentage: null, // Transparently null because ML model is in simulation
    model_connected: false,
    data_source: "Demo Geospatial Hazard Model (Simulation Mode)",
    last_update: TEN_MINS_AGO,
    is_demo: true,
    notes: "High soil saturation index (>85%) following continuous 72h monsoon rainfall.",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "risk-2",
    location: "Kaziranga National Park NH-715 Animal Corridors",
    district: "Golaghat & Nagaon",
    state: "Assam",
    risk_type: "flood",
    risk_level: "HIGH",
    expected_time_window: "Next 24 to 48 hours",
    confidence_percentage: null,
    model_connected: false,
    data_source: "Demo Hydrological Model (Simulation Mode)",
    last_update: THIRTY_MINS_AGO,
    is_demo: true,
    notes: "Brahmaputra water level rising 0.4m above danger mark at Nematighat.",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "risk-3",
    location: "Cherrapunji - Mawsynram Escarpment Road",
    district: "East Khasi Hills",
    state: "Meghalaya",
    risk_type: "road_disruption",
    risk_level: "MEDIUM",
    expected_time_window: "Today afternoon",
    confidence_percentage: null,
    model_connected: false,
    data_source: "Demo Meteorological Model (Simulation Mode)",
    last_update: THIRTY_MINS_AGO,
    is_demo: true,
    notes: "Ultra-heavy downpour causing localized zero-visibility and standing water sheets.",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "risk-4",
    location: "Singtam - Rangpo Valley Road",
    district: "East Sikkim",
    state: "Sikkim",
    risk_type: "landslide",
    risk_level: "HIGH",
    expected_time_window: "Next 12 hours",
    confidence_percentage: null,
    model_connected: false,
    data_source: "Demo Landslide Early Warning (Simulation Mode)",
    last_update: TEN_MINS_AGO,
    is_demo: true,
    notes: "Active slope shifting recorded on hillside geophones.",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 4. AI ALTERNATE ROUTE SUGGESTIONS
// ---------------------------------------------------------------------------
export const DEMO_ROUTE_SUGGESTIONS: RouteSuggestion[] = [
  {
    id: "route-sugg-1",
    start_location: "Guwahati (Assam)",
    destination: "Silchar (Barak Valley, Assam)",
    current_route: {
      name: "Via NH-27 (Lumding - Haflong - Silchar)",
      distance_km: 330,
      estimated_time_min: 660,
      status: "BLOCKED",
      problem_description: "Blockage at Jatinga Valley due to landslide debris clearance.",
    },
    alternative_routes: [
      {
        route_id: "alt-1",
        route_name: "Alternative Route 1: Via Meghalaya (NH-6)",
        via: "Guwahati -> Shillong -> Lad Rymbai -> Khliehriat -> Silchar",
        approx_distance_km: 375,
        estimated_travel_time_min: 540,
        accessibility_status: "PARTIAL",
        known_disruption: "Single lane traffic near Sonapur tunnel; delays 30-45 mins.",
        recommendation_reason: "Recommended primary bypass. All medical and petroleum transport currently routed here.",
        fuel_stops_available: true,
      },
      {
        route_id: "alt-2",
        route_name: "Alternative Route 2: Inter-Modal Rail RORO Corridor",
        via: "Guwahati New Goods Yard -> Lumding -> Badarpur Junction",
        approx_distance_km: 310,
        estimated_travel_time_min: 720,
        accessibility_status: "OPEN",
        known_disruption: "Scheduled rail slot availability required.",
        recommendation_reason: "Safe backup for bulk non-perishable freight and heavy emergency machinery.",
        fuel_stops_available: true,
      },
    ],
    mapping_api_connected: false,
    source: "Demo Routing Engine (Simulation Mode)",
    last_updated: TEN_MINS_AGO,
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "route-sugg-2",
    start_location: "Tezpur (Assam)",
    destination: "Tawang (Arunachal Pradesh)",
    current_route: {
      name: "Via NH-13 Bhalukpong Ghat",
      distance_km: 315,
      estimated_time_min: 600,
      status: "PARTIAL",
      problem_description: "Bhalukpong tributary bridge repair and Sela Pass fog.",
    },
    alternative_routes: [
      {
        route_id: "alt-2-1",
        route_name: "Alternative Route 1: Via Orang - Kalaktang - Rupa Bypass",
        via: "Tezpur -> Orang -> Kalaktang -> Shergaon -> Rupa -> Dirang -> Tawang",
        approx_distance_km: 340,
        estimated_travel_time_min: 620,
        accessibility_status: "OPEN",
        known_disruption: "Narrow stretches near Shergaon; heavy fog after 5 PM.",
        recommendation_reason: "Completely avoids the Bhalukpong bridge obstruction. Safe for ambulances and light logistics.",
        fuel_stops_available: true,
      },
    ],
    mapping_api_connected: false,
    source: "Demo Routing Engine (Simulation Mode)",
    last_updated: THIRTY_MINS_AGO,
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 5. TRAVEL DELAY ESTIMATION
// ---------------------------------------------------------------------------
export const DEMO_TRAVEL_DELAYS: TravelDelayRecord[] = [
  {
    id: "delay-1",
    route_name: "NH-27 Lumding to Silchar",
    origin: "Lumding",
    destination: "Silchar",
    district: "Dima Hasao",
    state: "Assam",
    normal_travel_time_min: 360,
    current_estimated_travel_time_min: 780,
    delay_min: 420,
    reason_for_delay: "Landslide",
    reason_description: "Debris clearance in progress at Jatinga. One-way intermittent convoys only.",
    last_updated: TEN_MINS_AGO,
    source: "Demo Traffic Telematics (Simulation)",
    is_live_source_connected: false,
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "delay-2",
    route_name: "NH-6 Shillong to Jowai",
    origin: "Shillong",
    destination: "Jowai",
    district: "East Khasi / West Jaintia",
    state: "Meghalaya",
    normal_travel_time_min: 90,
    current_estimated_travel_time_min: 150,
    delay_min: 60,
    reason_for_delay: "Weather disruption",
    reason_description: "Dense cloud cover and heavy rainfall causing crawl speed (20 km/h).",
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Traffic Telematics (Simulation)",
    is_live_source_connected: false,
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "delay-3",
    route_name: "NH-10 Sevoke to Gangtok",
    origin: "Siliguri / Sevoke",
    destination: "Gangtok",
    district: "East Sikkim",
    state: "Sikkim",
    normal_travel_time_min: 240,
    current_estimated_travel_time_min: 450,
    delay_min: 210,
    reason_for_delay: "Flood",
    reason_description: "River Teesta backflow over roadway; traffic rerouted through secondary hill roads.",
    last_updated: TEN_MINS_AGO,
    source: "Demo Traffic Telematics (Simulation)",
    is_live_source_connected: false,
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "delay-4",
    route_name: "NH-2 Kohima to Dimapur Bypass",
    origin: "Dimapur",
    destination: "Kohima",
    district: "Kohima",
    state: "Nagaland",
    normal_travel_time_min: 120,
    current_estimated_travel_time_min: 145,
    delay_min: 25,
    reason_for_delay: "Bridge restriction",
    reason_description: "Single-file truck queue at Chiephobozou culvert repair.",
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Traffic Telematics (Simulation)",
    is_live_source_connected: false,
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 6. GPS VEHICLE TRACKING
// ---------------------------------------------------------------------------
export const DEMO_VEHICLES: VehicleTrackingRecord[] = [
  {
    id: "veh-1",
    vehicle_id: "AS-01-GC-4482",
    vehicle_type: "Essential Carrier",
    driver_name_masked: "R. B***h (Authorized Driver)",
    current_location: {
      lat: 25.176,
      lng: 92.234,
      address: "Lad Rymbai Toll Junction, NH-6, Meghalaya",
    },
    destination: {
      lat: 24.833,
      lng: 92.778,
      address: "Civil Hospital & PDS Central Depot, Silchar, Assam",
    },
    route_name: "Guwahati-Shillong-Silchar Essential Corridor",
    status: "IN TRANSIT",
    last_gps_update: "3 minutes ago",
    eta: "Today 16:45 IST",
    route_path_points: [
      [26.144, 91.736],
      [25.578, 91.893],
      [25.176, 92.234],
      [24.833, 92.778],
    ],
    tracking_permission_granted: true,
    authorized_roles_only: true,
    is_gps_hardware_connected: false,
    is_demo: true,
    source: "Demo GPS Telematics Engine (Simulation Mode)",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "veh-2",
    vehicle_id: "AS-11-BC-9011",
    vehicle_type: "Van",
    driver_name_masked: "M. D***a (Medical Logistics)",
    current_location: {
      lat: 25.021,
      lng: 93.012,
      address: "Harangajao Safe Staging Post, Dima Hasao, Assam",
    },
    destination: {
      lat: 24.825,
      lng: 92.801,
      address: "Primary Health Centre (PHC), Haflong, Assam",
    },
    route_name: "Haflong Hill Medical Feeder",
    status: "DELAYED",
    last_gps_update: "8 minutes ago",
    eta: "Today 19:30 IST (Delayed by mudslide)",
    route_path_points: [
      [25.168, 93.031],
      [25.021, 93.012],
      [24.825, 92.801],
    ],
    tracking_permission_granted: true,
    authorized_roles_only: true,
    is_gps_hardware_connected: false,
    is_demo: true,
    source: "Demo GPS Telematics Engine (Simulation Mode)",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "veh-3",
    vehicle_id: "AR-01-T-3390",
    vehicle_type: "Truck",
    driver_name_masked: "K. T***o (Certified Logistics)",
    current_location: {
      lat: 27.351,
      lng: 92.228,
      address: "Dirang Valley Checkpost, West Kameng, Arunachal Pradesh",
    },
    destination: {
      lat: 27.586,
      lng: 91.865,
      address: "District Disaster Relief Store, Tawang, Arunachal Pradesh",
    },
    route_name: "Tezpur-Kalaktang-Tawang Bypass",
    status: "IN TRANSIT",
    last_gps_update: "12 minutes ago",
    eta: "Today 20:15 IST",
    route_path_points: [
      [26.652, 92.792],
      [27.112, 92.215],
      [27.351, 92.228],
      [27.586, 91.865],
    ],
    tracking_permission_granted: true,
    authorized_roles_only: true,
    is_gps_hardware_connected: false,
    is_demo: true,
    source: "Demo GPS Telematics Engine (Simulation Mode)",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 7. ESSENTIAL GOODS SHIPMENTS
// ---------------------------------------------------------------------------
export const DEMO_ESSENTIAL_SHIPMENTS: EssentialShipmentRecord[] = [
  {
    id: "ship-1",
    shipment_id: "NER-MED-2026-081",
    vehicle_id: "AS-01-GC-4482",
    goods_category: "Medicines",
    priority: "CRITICAL_PRIORITY",
    is_medicine_priority: true,
    origin: "Central Medical Warehouse, Guwahati (Assam)",
    destination: "Silchar Medical College & Hospital (SMCH), Cachar",
    current_location: "Lad Rymbai, NH-6, Meghalaya",
    status: "IN TRANSIT",
    dispatch_time: "06:00 AM Today",
    expected_arrival: "04:45 PM Today",
    delay_status: "On-Track via Alt Route 1",
    delay_min: 30,
    contents_summary: "Cold-chain insulin, dialysis fluids, cardiac amlodipine, antibiotics (1,200 units)",
    consignee_type: "Hospital",
    last_updated: TEN_MINS_AGO,
    is_demo: true,
    source: "Demo Logistics Management System (Simulation)",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "ship-2",
    shipment_id: "NER-MED-2026-082",
    vehicle_id: "AS-11-BC-9011",
    goods_category: "Medicines",
    priority: "CRITICAL_PRIORITY",
    is_medicine_priority: true,
    origin: "District Dispensary, Lumding",
    destination: "Sub-Divisional Civil Hospital, Haflong",
    current_location: "Harangajao Staging Post, Dima Hasao",
    status: "DELAYED",
    dispatch_time: "07:30 AM Today",
    expected_arrival: "07:30 PM Today (Revised)",
    delay_status: "Delayed +4.5h due to Jatinga landslide",
    delay_min: 270,
    contents_summary: "Emergency trauma kits, intravenous saline, antivenom serums (450 units)",
    consignee_type: "Hospital",
    last_updated: TEN_MINS_AGO,
    is_demo: true,
    source: "Demo Logistics Management System (Simulation)",
    created_at: TWO_HOURS_AGO,
    updated_at: TEN_MINS_AGO,
  },
  {
    id: "ship-3",
    shipment_id: "NER-FOOD-2026-114",
    vehicle_id: "AR-01-T-3390",
    goods_category: "Food",
    priority: "HIGH",
    is_medicine_priority: false,
    origin: "FCI Grain Silo, Tezpur (Assam)",
    destination: "Civil Supplies Food Grain Godown, Tawang",
    current_location: "Dirang Valley, West Kameng",
    status: "IN TRANSIT",
    dispatch_time: "05:00 AM Today",
    expected_arrival: "08:15 PM Today",
    delay_status: "Normal Transit via Kalaktang",
    delay_min: 20,
    contents_summary: "Fortified rice, pulses, wheat flour, baby nutritional porridge (8.5 MT)",
    consignee_type: "PDS Depot",
    last_updated: THIRTY_MINS_AGO,
    is_demo: true,
    source: "Demo Logistics Management System (Simulation)",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "ship-4",
    shipment_id: "NER-WAT-2026-042",
    vehicle_id: "MN-01-W-5512",
    goods_category: "Drinking water",
    priority: "HIGH",
    is_medicine_priority: false,
    origin: "Water Treatment Plant, Imphal West",
    destination: "Disaster Relief Camp, Churachandpur",
    current_location: "Bishnupur Highway Sector",
    status: "DISPATCHED",
    dispatch_time: "09:00 AM Today",
    expected_arrival: "01:30 PM Today",
    delay_status: "On Schedule",
    delay_min: 0,
    contents_summary: "Packaged sterile drinking water cans (5,000 Litres) & water purification chlorine tablets",
    consignee_type: "Disaster Relief",
    last_updated: THIRTY_MINS_AGO,
    is_demo: true,
    source: "Demo Logistics Management System (Simulation)",
    created_at: TWO_HOURS_AGO,
    updated_at: THIRTY_MINS_AGO,
  },
  {
    id: "ship-5",
    shipment_id: "NER-AGR-2026-039",
    vehicle_id: "MZ-01-A-1102",
    goods_category: "Agricultural supplies",
    priority: "NORMAL",
    is_medicine_priority: false,
    origin: "Fertilizer Depot, Silchar",
    destination: "Farmers Cooperative Warehouse, Aizawl",
    current_location: "Vairengte Border Post, Mizoram",
    status: "ARRIVED",
    dispatch_time: "Yesterday 08:00 AM",
    expected_arrival: "Today 08:30 AM",
    delay_status: "Delivered Successfully",
    delay_min: 0,
    contents_summary: "High-yield organic paddy seeds and drip-irrigation piping sets",
    consignee_type: "Community Center",
    last_updated: TWO_HOURS_AGO,
    is_demo: true,
    source: "Demo Logistics Management System (Simulation)",
    created_at: TWO_HOURS_AGO,
    updated_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 8. BLOCKED ROAD ALERTS
// ---------------------------------------------------------------------------
export const DEMO_BLOCKED_ALERTS: BlockedRoadAlert[] = [
  {
    id: "alert-1",
    road_name: "NH-27 Lumding - Silchar Highway",
    location: "Jatinga Valley km 142",
    district: "Dima Hasao",
    state: "Assam",
    reason: "Severe landslide following heavy torrential rains",
    timestamp: "Today 05:30 AM",
    suggested_action: "Check alternate route via Meghalaya (NH-6) or defer non-emergency travel",
    is_active: true,
    severity: "CRITICAL",
    source: "Assam State Disaster Management Authority (ASDMA Simulated Feed)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "alert-2",
    road_name: "NH-10 Sevoke - Gangtok Highway",
    location: "29th Mile Teesta Scour Section",
    district: "East Sikkim / Kalimpong",
    state: "Sikkim",
    reason: "Teesta river overflow and road shoulder erosion",
    timestamp: "Today 07:15 AM",
    suggested_action: "Check alternate route via Mungpoo - Labha - Damdim corridor",
    is_active: true,
    severity: "HIGH",
    source: "Sikkim Disaster Cell (Simulated Feed)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "alert-3",
    road_name: "Bhalukpong - Tawang Approach Bridge",
    location: "Kameng Crossing Bridge km 18",
    district: "West Kameng",
    state: "Arunachal Pradesh",
    reason: "Bridge pier structural reinforcement under emergency repair",
    timestamp: "Yesterday 09:00 PM",
    suggested_action: "Check alternate route via Kalaktang - Rupa Bypass",
    is_active: true,
    severity: "HIGH",
    source: "Border Roads Organisation (Simulated Feed)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 9. FIELD INCIDENT REPORTS
// ---------------------------------------------------------------------------
export const DEMO_INCIDENT_REPORTS: FieldIncidentReport[] = [
  {
    id: "inc-1",
    incident_type: "Landslide",
    photo_name: "jatinga_slope_mudslide.jpg",
    description: "Rock and mud debris blocking both lanes of NH-27 near Jatinga Railway overpass. Two bulldozers working on clearance.",
    gps_location: {
      lat: 25.124,
      lng: 93.042,
      address: "Near Jatinga Overpass, NH-27, Dima Hasao, Assam",
    },
    district: "Dima Hasao",
    state: "Assam",
    timestamp: "Today 06:10 AM",
    reporter_id_masked: "AS-HW-Officer-42",
    verification_status: "OFFICIAL_VERIFIED",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "inc-2",
    incident_type: "Flood",
    photo_name: "kaziranga_culvert_overflow.jpg",
    description: "Brahmaputra overflow water reaching 15cm above pavement on NH-715 near Kohora. Speed limit restricted to 20 km/h.",
    gps_location: {
      lat: 26.583,
      lng: 93.411,
      address: "Kohora Range, NH-715, Golaghat, Assam",
    },
    district: "Golaghat",
    state: "Assam",
    timestamp: "Today 07:45 AM",
    reporter_id_masked: "FR-Volunteer-19",
    verification_status: "COMMUNITY_REPORTED",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "inc-3",
    incident_type: "Bridge damage",
    photo_name: "bhalukpong_bridge_piers.jpg",
    description: "Flash flood torrent caused scouring on southern abutment. Heavy cargo halted until safety inspection completes.",
    gps_location: {
      lat: 27.014,
      lng: 92.651,
      address: "Bhalukpong River Bridge, West Kameng, Arunachal Pradesh",
    },
    district: "West Kameng",
    state: "Arunachal Pradesh",
    timestamp: "Yesterday 08:30 PM",
    reporter_id_masked: "BRO-Engg-Team",
    verification_status: "OFFICIAL_VERIFIED",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 10. DISTRICT CONNECTIVITY DASHBOARD
// ---------------------------------------------------------------------------
export const DEMO_DISTRICT_CONNECTIVITY: DistrictConnectivityRecord[] = [
  {
    id: "dist-1",
    district_name: "Kamrup Metropolitan (Guwahati)",
    state: "Assam",
    connectivity_status: "GOOD CONNECTIVITY",
    open_routes_count: 8,
    blocked_routes_count: 0,
    partial_routes_count: 1,
    active_incidents_count: 1,
    essential_goods_delays_count: 0,
    last_updated: TEN_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-2",
    district_name: "Dima Hasao (Haflong)",
    state: "Assam",
    connectivity_status: "SEVERELY DISRUPTED",
    open_routes_count: 1,
    blocked_routes_count: 3,
    partial_routes_count: 2,
    active_incidents_count: 4,
    essential_goods_delays_count: 5,
    last_updated: TEN_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-3",
    district_name: "Cachar (Silchar)",
    state: "Assam",
    connectivity_status: "PARTIAL CONNECTIVITY",
    open_routes_count: 3,
    blocked_routes_count: 1,
    partial_routes_count: 2,
    active_incidents_count: 2,
    essential_goods_delays_count: 3,
    last_updated: TEN_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-4",
    district_name: "East Khasi Hills (Shillong)",
    state: "Meghalaya",
    connectivity_status: "GOOD CONNECTIVITY",
    open_routes_count: 6,
    blocked_routes_count: 0,
    partial_routes_count: 2,
    active_incidents_count: 1,
    essential_goods_delays_count: 1,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-5",
    district_name: "West Kameng & Tawang",
    state: "Arunachal Pradesh",
    connectivity_status: "PARTIAL CONNECTIVITY",
    open_routes_count: 2,
    blocked_routes_count: 1,
    partial_routes_count: 3,
    active_incidents_count: 3,
    essential_goods_delays_count: 2,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-6",
    district_name: "Imphal West & East",
    state: "Manipur",
    connectivity_status: "PARTIAL CONNECTIVITY",
    open_routes_count: 4,
    blocked_routes_count: 0,
    partial_routes_count: 2,
    active_incidents_count: 2,
    essential_goods_delays_count: 2,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-7",
    district_name: "East Sikkim (Gangtok)",
    state: "Sikkim",
    connectivity_status: "DISRUPTED",
    open_routes_count: 2,
    blocked_routes_count: 2,
    partial_routes_count: 2,
    active_incidents_count: 3,
    essential_goods_delays_count: 4,
    last_updated: TEN_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-8",
    district_name: "Aizawl & Kolasib",
    state: "Mizoram",
    connectivity_status: "GOOD CONNECTIVITY",
    open_routes_count: 5,
    blocked_routes_count: 0,
    partial_routes_count: 1,
    active_incidents_count: 0,
    essential_goods_delays_count: 0,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-9",
    district_name: "Kohima & Dimapur",
    state: "Nagaland",
    connectivity_status: "PARTIAL CONNECTIVITY",
    open_routes_count: 4,
    blocked_routes_count: 0,
    partial_routes_count: 2,
    active_incidents_count: 1,
    essential_goods_delays_count: 1,
    last_updated: THIRTY_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
  {
    id: "dist-10",
    district_name: "West Tripura (Agartala)",
    state: "Tripura",
    connectivity_status: "GOOD CONNECTIVITY",
    open_routes_count: 7,
    blocked_routes_count: 0,
    partial_routes_count: 1,
    active_incidents_count: 0,
    essential_goods_delays_count: 0,
    last_updated: TEN_MINS_AGO,
    source: "Demo Regional Transport Dataset (Simulation)",
    is_demo: true,
  },
];

// ---------------------------------------------------------------------------
// 11. LOGISTICS BOTTLENECK MONITORING
// ---------------------------------------------------------------------------
export const DEMO_BOTTLENECKS: LogisticsBottleneck[] = [
  {
    id: "bot-1",
    location: "Jatinga Hill Choke Point",
    district: "Dima Hasao",
    state: "Assam",
    issue: "Landslide & severe mud debris accumulation",
    affected_route: "NH-27 East-West Arterial Corridor",
    severity: "CRITICAL",
    affected_shipment_count: 14,
    is_shipment_data_available: true,
    last_update: TEN_MINS_AGO,
    source: "Demo Freight Control (Simulation)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "bot-2",
    location: "Sonapur Tunnel Single-Lane Funnel",
    district: "East Jaintia Hills",
    state: "Meghalaya",
    issue: "Bridge restriction & single-lane diversion",
    affected_route: "NH-6 Barak Valley Lifeline",
    severity: "HIGH",
    affected_shipment_count: 8,
    is_shipment_data_available: true,
    last_update: THIRTY_MINS_AGO,
    source: "Demo Freight Control (Simulation)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "bot-3",
    location: "Teesta Low Level Corridor (29th Mile)",
    district: "Kalimpong border",
    state: "Sikkim",
    issue: "Flood & river embankment subsidence",
    affected_route: "NH-10 Sevoke - Gangtok Corridor",
    severity: "CRITICAL",
    affected_shipment_count: null, // "Data unavailable" per spec instruction 11
    is_shipment_data_available: false,
    last_update: TEN_MINS_AGO,
    source: "Demo Freight Control (Simulation)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 12. EMERGENCY / DISASTER ACCESSIBILITY ROUTES
// ---------------------------------------------------------------------------
export const DEMO_EMERGENCY_ROUTES: EmergencyRoute[] = [
  {
    id: "em-1",
    route_name: "Guwahati - Shillong - Silchar Green Corridor",
    category: "Medical Access Route",
    start_location: "Guwahati Medical College & Hospital (GMCH)",
    destination: "Silchar Medical College & Hospital (SMCH)",
    accessibility_status: "PARTIAL",
    known_disruption: "Sonapur tunnel regulated single-lane; priority escort provided for ambulances",
    is_official_verified: true,
    verified_by_agency: "Joint ASDMA & Meghalaya SDRF Authority",
    advisory_notice: "Officially designated Emergency Medical Corridor. Civilian non-essential trucks restricted.",
    last_update: TEN_MINS_AGO,
    source: "State Emergency Operations Center (SEOC Simulated Feed)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "em-2",
    route_name: "Kalaktang - Rupa Medical Emergency Feeder",
    category: "Emergency Route",
    start_location: "Orang Army Hospital / Tezpur Civil",
    destination: "Tawang District Hospital",
    accessibility_status: "OPEN",
    known_disruption: "Narrow hairpin turns near Shergaon; 4x4 or snow chains mandatory after 6 PM",
    is_official_verified: false,
    advisory_notice: "Suggested emergency-access route. Official verification pending morning inspection.",
    last_update: THIRTY_MINS_AGO,
    source: "Civilian Relief Coordination Feed (Simulation)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "em-3",
    route_name: "Badarpur - Karimganj - Dharmanagar Corridor",
    category: "Essential Goods Route",
    start_location: "Badarpur Rail Hub (Assam)",
    destination: "Dharmanagar Depot (Tripura)",
    accessibility_status: "OPEN",
    known_disruption: "Minor waterlogging on side shoulders; carriageway fully motorable",
    is_official_verified: true,
    verified_by_agency: "Tripura State Disaster Management Authority",
    advisory_notice: "Designated Essential Goods Lifeline for Tripura & South Assam.",
    last_update: TEN_MINS_AGO,
    source: "State Transport Authority (Simulated Feed)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
  {
    id: "em-4",
    route_name: "Teesta Mungpoo Hill Bypass",
    category: "Evacuation Route",
    start_location: "Rangpo Border Checkpost",
    destination: "Siliguri Staging Grounds",
    accessibility_status: "PARTIAL",
    known_disruption: "Steep gradient; single axle light vehicles and ambulances only",
    is_official_verified: false,
    advisory_notice: "Suggested emergency-access route. Proceed with caution under local administration guidance.",
    last_update: TEN_MINS_AGO,
    source: "Sikkim Local Advisory (Simulation)",
    is_demo: true,
    created_at: TWO_HOURS_AGO,
  },
];

// ---------------------------------------------------------------------------
// 13. WEATHER DATA RECORDS
// ---------------------------------------------------------------------------
export const DEMO_WEATHER_RECORDS: WeatherDataRecord[] = [
  {
    id: "wx-1",
    district: "Dima Hasao",
    state: "Assam",
    temperature_c: 23.4,
    condition: "Torrential Rain & Thunderstorms",
    rainfall_mm_24h: 142.5,
    is_heavy_rainfall: true,
    flood_related_risk: "CRITICAL",
    weather_alerts: ["Red Alert: Intense precipitation likely to trigger slope failures in hilly tracts"],
    is_api_connected: false,
    source: "Demo Weather Feed (India Meteorological Dept Format Simulation)",
    last_updated: TEN_MINS_AGO,
    is_demo: true,
  },
  {
    id: "wx-2",
    district: "Kamrup Metropolitan",
    state: "Assam",
    temperature_c: 28.2,
    condition: "Scattered Rain Showers",
    rainfall_mm_24h: 38.0,
    is_heavy_rainfall: false,
    flood_related_risk: "LOW",
    weather_alerts: ["Yellow Alert: Periodic urban waterlogging in low lying municipal drains"],
    is_api_connected: false,
    source: "Demo Weather Feed (IMD Format Simulation)",
    last_updated: TEN_MINS_AGO,
    is_demo: true,
  },
  {
    id: "wx-3",
    district: "East Khasi Hills (Cherrapunji / Shillong)",
    state: "Meghalaya",
    temperature_c: 19.5,
    condition: "Continuous Heavy Rainfall & Dense Fog",
    rainfall_mm_24h: 185.0,
    is_heavy_rainfall: true,
    flood_related_risk: "HIGH",
    weather_alerts: ["Orange Alert: Highway visibility below 50m on high plateau crests"],
    is_api_connected: false,
    source: "Demo Weather Feed (IMD Format Simulation)",
    last_updated: THIRTY_MINS_AGO,
    is_demo: true,
  },
  {
    id: "wx-4",
    district: "East Sikkim (Gangtok)",
    state: "Sikkim",
    temperature_c: 17.0,
    condition: "Monsoon Downpour",
    rainfall_mm_24h: 110.0,
    is_heavy_rainfall: true,
    flood_related_risk: "HIGH",
    weather_alerts: ["Orange Alert: Fast river currents and hillside mud slips along NH-10"],
    is_api_connected: false,
    source: "Demo Weather Feed (IMD Format Simulation)",
    last_updated: TEN_MINS_AGO,
    is_demo: true,
  },
];

// ---------------------------------------------------------------------------
// 14. TRANSPORT DATA SOURCES
// ---------------------------------------------------------------------------
export const DEMO_TRANSPORT_DATA_SOURCES: TransportDataSource[] = [
  {
    id: "src-1",
    name: "National Highways Authority (NHAI / NE Division)",
    type: "ROUTING_API",
    is_connected: false,
    endpoint: "https://api.transport.gov.in/ner/v1",
    last_ping: undefined,
    status_label: "Not Connected (Demo Mode)",
  },
  {
    id: "src-2",
    name: "India Meteorological Department (IMD NER Regional Feed)",
    type: "WEATHER_API",
    is_connected: false,
    endpoint: "https://api.imd.gov.in/regional/guwahati",
    last_ping: undefined,
    status_label: "Not Connected (Demo Mode)",
  },
  {
    id: "src-3",
    name: "State Transport Fleet Telematics & GPS Gateway",
    type: "GPS_TELEMATICS",
    is_connected: false,
    endpoint: "https://fleet.ner-logistics.org/gps/stream",
    last_ping: undefined,
    status_label: "Not Connected (Demo Mode)",
  },
  {
    id: "src-4",
    name: "North East Essential Supplies Tracking Registry",
    type: "STATE_TRANSPORT_DB",
    is_connected: false,
    endpoint: "postgresql://logistics-db.ner.gov:5432/supplies",
    last_ping: undefined,
    status_label: "Not Connected (Demo Mode)",
  },
  {
    id: "src-5",
    name: "State Disaster Management Authorities (SDMA Emergency Network)",
    type: "DISASTER_MGMT_FEED",
    is_connected: false,
    endpoint: "https://sdma.ner.gov.in/api/incidents",
    last_ping: undefined,
    status_label: "Not Connected (Demo Mode)",
  },
];
